-- Recyclon Supabase PostgreSQL schema
-- Paste into Supabase Dashboard -> SQL Editor -> New query -> Run.
-- This preserves the existing PHP application's table and column names.
-- It intentionally contains no production users, passwords, or private data.

create extension if not exists pgcrypto;

create table if not exists public.users (
    user_id bigint generated by default as identity primary key,
    auth_user_id uuid unique,
    name varchar(100) not null,
    email varchar(255) unique,
    password varchar(255),
    phone varchar(32),
    ic_number varchar(64),
    bank_name varchar(100),
    bank_account_number varchar(100),
    role text check (role in ('Admin', 'Staff', 'Driver', 'Customer')),
    address varchar(255),
    status text not null default 'Active' check (status in ('Active', 'Inactive')),
    created_at timestamptz not null default now(),
    google_id varchar(255),
    auto_accept_bookings boolean not null default false
);

-- Keep existing Supabase projects compatible when this schema is re-applied.
alter table public.users
    add column if not exists auto_accept_bookings boolean not null default false;

create table if not exists public.lorries (
    lorry_id bigint generated by default as identity primary key,
    plate_number varchar(20) not null unique,
    driver_id bigint references public.users(user_id) on delete set null,
    status text not null default 'Available' check (status in ('Available', 'On Duty', 'Maintenance')),
    current_lat numeric(10,7),
    current_long numeric(10,7),
    last_updated timestamptz,
    destination_lat double precision,
    destination_long double precision,
    destination_set_at timestamptz
);

create table if not exists public.waste_categories (
    waste_id bigint generated by default as identity primary key,
    category_name varchar(50) not null,
    unit_price numeric(10,2),
    unit varchar(10) not null default 'kg',
    image_icon varchar(255),
    status text not null default 'Active' check (status in ('Active', 'Inactive'))
);

create table if not exists public.booking (
    booking_id bigint generated by default as identity primary key,
    customer_id bigint references public.users(user_id) on delete set null,
    driver_id bigint references public.users(user_id) on delete set null,
    customer_name varchar(100),
    staff_id bigint references public.users(user_id) on delete set null,
    lorry_id bigint references public.lorries(lorry_id) on delete set null,
    address varchar(255) not null default '',
    note text,
    pickup_date date,
    booking_date date not null default current_date,
    scheduled_date timestamptz,
    status text not null default 'Pending' check (status in ('Pending', 'Scheduled', 'Completed', 'Cancelled', 'Confirmed')),
    booking_type text not null default 'pickup' check (booking_type in ('pickup', 'walkin')),
    created_at timestamptz not null default now()
);

create table if not exists public.sales (
    sale_id bigint generated by default as identity primary key,
    customer_id bigint references public.users(user_id) on delete set null,
    staff_id bigint references public.users(user_id) on delete set null,
    booking_id bigint references public.booking(booking_id) on delete set null,
    lorry_id bigint references public.lorries(lorry_id) on delete set null,
    total_amount numeric(10,2) not null default 0,
    sale_date timestamptz not null default now(),
    payment_status text not null default 'Pending' check (payment_status in ('Paid', 'Pending', 'Cancelled'))
);

create table if not exists public.sale_items (
    item_id bigint generated by default as identity primary key,
    sale_id bigint references public.sales(sale_id) on delete cascade,
    waste_id bigint references public.waste_categories(waste_id) on delete set null,
    weight_kg numeric(10,2),
    price_per_kg numeric(10,2),
    subtotal numeric(10,2)
);

create table if not exists public.price_history (
    history_id bigint generated by default as identity primary key,
    waste_id bigint references public.waste_categories(waste_id) on delete set null,
    old_price numeric(10,2),
    new_price numeric(10,2),
    changed_by bigint references public.users(user_id) on delete set null,
    changed_at timestamptz not null default now()
);

create table if not exists public.gps_log (
    log_id bigint generated by default as identity primary key,
    lorry_id bigint not null references public.lorries(lorry_id) on delete cascade,
    latitude numeric(10,7) not null,
    longitude numeric(10,7) not null,
    recorded_at timestamptz not null default now()
);

create table if not exists public.arrival_queue (
    id bigint generated by default as identity primary key,
    booking_id bigint references public.booking(booking_id) on delete set null,
    driver_id bigint references public.users(user_id) on delete set null,
    assigned_lorry_id bigint references public.lorries(lorry_id) on delete set null,
    created_by bigint references public.users(user_id) on delete set null,
    driver_name varchar(255),
    plate_number varchar(64),
    geolocation varchar(255),
    location_name varchar(255),
    latitude numeric(10,7),
    longitude numeric(10,7),
    priority integer not null default 100,
    notes text,
    status text not null default 'pending' check (status in ('pending', 'ongoing', 'completed', 'cancelled')),
    assigned_at timestamptz,
    completed_at timestamptz,
    updated_at timestamptz not null default now(),
    created_at timestamptz not null default now()
);

-- Add newer columns when an older Supabase schema already exists.
alter table public.users add column if not exists auth_user_id uuid;
alter table public.lorries add column if not exists destination_set_at timestamptz;
alter table public.booking add column if not exists booking_type text not null default 'pickup';
alter table public.arrival_queue add column if not exists booking_id bigint;
alter table public.arrival_queue add column if not exists driver_id bigint;
alter table public.arrival_queue add column if not exists assigned_lorry_id bigint;
alter table public.arrival_queue add column if not exists created_by bigint;
alter table public.arrival_queue add column if not exists location_name varchar(255);
alter table public.arrival_queue add column if not exists latitude numeric(10,7);
alter table public.arrival_queue add column if not exists longitude numeric(10,7);
alter table public.arrival_queue add column if not exists priority integer not null default 100;
alter table public.arrival_queue add column if not exists notes text;
alter table public.arrival_queue add column if not exists assigned_at timestamptz;
alter table public.arrival_queue add column if not exists completed_at timestamptz;
alter table public.arrival_queue add column if not exists updated_at timestamptz not null default now();

create unique index if not exists users_email_lower_idx on public.users (lower(email)) where email is not null;
create index if not exists booking_customer_idx on public.booking (customer_id);
create index if not exists booking_status_date_idx on public.booking (status, booking_date);
create index if not exists booking_driver_idx on public.booking (driver_id);
create index if not exists lorries_driver_idx on public.lorries (driver_id);
create index if not exists gps_log_lorry_recorded_idx on public.gps_log (lorry_id, recorded_at desc);
create index if not exists queue_status_priority_idx on public.arrival_queue (status, priority, created_at);
create index if not exists queue_lorry_idx on public.arrival_queue (assigned_lorry_id, status);
create index if not exists queue_driver_idx on public.arrival_queue (driver_id, status);
create index if not exists sales_booking_idx on public.sales (booking_id);
create index if not exists sale_items_sale_idx on public.sale_items (sale_id);
create index if not exists price_history_waste_idx on public.price_history (waste_id, changed_at desc);

-- Starter pricing rows keep the new-booking form usable on a fresh project.
-- Existing categories are preserved; each row is inserted only when its name
-- is not already present.
insert into public.waste_categories (category_name, unit_price, unit, status)
select seed.category_name, seed.unit_price, seed.unit, 'Active'
from (values
    ('Paper Box', 1.00::numeric, 'kg'),
    ('Paper', 0.80::numeric, 'kg'),
    ('Metal', 2.50::numeric, 'kg'),
    ('Plastic', 1.50::numeric, 'kg'),
    ('Rubbish', 0.50::numeric, 'kg'),
    ('Tin', 0.80::numeric, 'kg')
) as seed(category_name, unit_price, unit)
where not exists (
    select 1 from public.waste_categories existing
    where lower(existing.category_name) = lower(seed.category_name)
);

-- Keep timestamps current for queue updates.
create or replace function public.set_arrival_queue_updated_at()
returns trigger language plpgsql as $$
begin
    new.updated_at = now();
    if new.status = 'ongoing' and old.status is distinct from 'ongoing' and new.assigned_at is null then
        new.assigned_at = now();
    end if;
    if new.status = 'completed' and old.status is distinct from 'completed' and new.completed_at is null then
        new.completed_at = now();
    end if;
    return new;
end;
$$;

drop trigger if exists arrival_queue_updated_at on public.arrival_queue;
create trigger arrival_queue_updated_at
before update on public.arrival_queue
for each row execute function public.set_arrival_queue_updated_at();

-- Supabase Auth role helpers. Link a row in users.auth_user_id to auth.users.id
-- when moving an account to Supabase Auth.
create or replace function public.current_app_role()
returns text language sql stable security definer set search_path = public
as $$ select role from public.users where auth_user_id = auth.uid() limit 1 $$;

alter table public.users enable row level security;
alter table public.lorries enable row level security;
alter table public.waste_categories enable row level security;
alter table public.booking enable row level security;
alter table public.sales enable row level security;
alter table public.sale_items enable row level security;
alter table public.price_history enable row level security;
alter table public.gps_log enable row level security;
alter table public.arrival_queue enable row level security;

drop policy if exists users_self_select on public.users;
create policy users_self_select on public.users for select to authenticated
using (auth_user_id = auth.uid() or public.current_app_role() in ('Admin', 'Staff'));

drop policy if exists users_admin_manage on public.users;
create policy users_admin_manage on public.users for all to authenticated
using (public.current_app_role() = 'Admin') with check (public.current_app_role() = 'Admin');

drop policy if exists waste_authenticated_read on public.waste_categories;
create policy waste_authenticated_read on public.waste_categories for select to authenticated using (true);
drop policy if exists waste_staff_manage on public.waste_categories;
create policy waste_staff_manage on public.waste_categories for all to authenticated
using (public.current_app_role() in ('Admin', 'Staff')) with check (public.current_app_role() in ('Admin', 'Staff'));

create or replace function public.can_access_booking(row_customer_id bigint, row_driver_id bigint, row_staff_id bigint)
returns boolean language sql stable security definer set search_path = public
as $$
    select public.current_app_role() in ('Admin', 'Staff')
        or exists (select 1 from public.users u where u.auth_user_id = auth.uid() and (u.user_id = row_customer_id or u.user_id = row_driver_id or u.user_id = row_staff_id));
$$;

drop policy if exists booking_access on public.booking;
create policy booking_access on public.booking for select to authenticated
using (public.can_access_booking(customer_id, driver_id, staff_id));
drop policy if exists booking_customer_insert on public.booking;
create policy booking_customer_insert on public.booking for insert to authenticated
with check (public.current_app_role() in ('Admin', 'Staff') or customer_id = (select user_id from public.users where auth_user_id = auth.uid()));
drop policy if exists booking_manage on public.booking;
create policy booking_manage on public.booking for update to authenticated
using (public.can_access_booking(customer_id, driver_id, staff_id))
with check (public.current_app_role() in ('Admin', 'Staff') or customer_id = (select user_id from public.users where auth_user_id = auth.uid()));
drop policy if exists booking_delete on public.booking;
create policy booking_delete on public.booking for delete to authenticated
using (public.current_app_role() in ('Admin', 'Staff') or customer_id = (select user_id from public.users where auth_user_id = auth.uid()));

drop policy if exists lorries_read on public.lorries;
create policy lorries_read on public.lorries for select to authenticated using (true);
drop policy if exists lorries_staff_manage on public.lorries;
create policy lorries_staff_manage on public.lorries for all to authenticated
using (public.current_app_role() in ('Admin', 'Staff')) with check (public.current_app_role() in ('Admin', 'Staff'));
drop policy if exists sales_access on public.sales;
create policy sales_access on public.sales for select to authenticated
using (public.current_app_role() in ('Admin', 'Staff') or customer_id = (select user_id from public.users where auth_user_id = auth.uid()));
drop policy if exists sale_items_access on public.sale_items;
create policy sale_items_access on public.sale_items for select to authenticated using (true);
drop policy if exists price_history_staff_read on public.price_history;
create policy price_history_staff_read on public.price_history for select to authenticated
using (public.current_app_role() in ('Admin', 'Staff'));
drop policy if exists gps_authenticated_read on public.gps_log;
create policy gps_authenticated_read on public.gps_log for select to authenticated using (true);
drop policy if exists gps_staff_insert on public.gps_log;
create policy gps_staff_insert on public.gps_log for insert to authenticated
with check (public.current_app_role() in ('Admin', 'Staff', 'Driver'));
drop policy if exists queue_authenticated_read on public.arrival_queue;
create policy queue_authenticated_read on public.arrival_queue for select to authenticated
using (public.current_app_role() in ('Admin', 'Staff') or driver_id = (select user_id from public.users where auth_user_id = auth.uid()));
drop policy if exists queue_staff_manage on public.arrival_queue;
create policy queue_staff_manage on public.arrival_queue for all to authenticated
using (public.current_app_role() in ('Admin', 'Staff')) with check (public.current_app_role() in ('Admin', 'Staff'));
drop policy if exists queue_driver_update on public.arrival_queue;
create policy queue_driver_update on public.arrival_queue for update to authenticated
using (driver_id = (select user_id from public.users where auth_user_id = auth.uid()))
with check (driver_id = (select user_id from public.users where auth_user_id = auth.uid()));

-- Realtime is useful for queue and fleet status screens.
alter table public.arrival_queue replica identity full;
alter table public.lorries replica identity full;
